# Generated by Django 4.2.7 on 2026-02-10 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Conversation", max_length=255)),
                ("subject", models.CharField(default="general", max_length=100)),
                (
                    "class_level",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("language", models.CharField(default="hindi", max_length=10)),
                ("message_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                (
                    "class_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("chapter", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("word_count", models.IntegerField(default=0)),
                ("language", models.CharField(default="hindi", max_length=10)),
                ("embeddings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["class_level", "subject", "chapter"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("text_content", models.TextField()),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ai_tutor/audio/"
                    ),
                ),
                ("audio_duration", models.IntegerField(blank=True, null=True)),
                ("transcribed_text", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_tutor.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TextbookContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="Source of content", max_length=200),
                ),
                (
                    "class_level",
                    models.CharField(help_text="Class level", max_length=20),
                ),
                ("subject", models.CharField(help_text="Subject name", max_length=100)),
                (
                    "chapter",
                    models.CharField(help_text="Chapter identifier", max_length=100),
                ),
                ("content", models.TextField(help_text="Actual content")),
                (
                    "embedding_id",
                    models.CharField(
                        help_text="ID in vector database", max_length=100, unique=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Textbook Content",
                "verbose_name_plural": "Textbook Contents",
                "db_table": "textbook_content",
                "ordering": ["class_level", "subject", "chapter"],
                "indexes": [
                    models.Index(
                        fields=["class_level", "subject"],
                        name="textbook_co_class_l_eb55fd_idx",
                    ),
                    models.Index(
                        fields=["subject"], name="textbook_co_subject_a08e75_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="ai_tutor/images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("ocr_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ai_tutor.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_tutor.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_messages", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("total_audio_seconds", models.IntegerField(default=0)),
                ("total_images", models.IntegerField(default=0)),
                ("subject_usage", models.JSONField(default=dict)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("satisfaction_rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
